# Generated by Django 4.2.8 on 2024-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
