# Generated by Django 4.2.8 on 2024-01-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_chat_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
